### ISSUE TITLE
Disable issue tracker and wiki

### ISSUE THREAD

**Issue by mikesherov** [TheAlphaNerd/nihilism#2]
If you don't care, these are superfluous.

**Comment by markmandel** [comment]
Leave them open, so that all deposited issues and worries disappear into the uncaring void.

This will be a valuable existential moment in their lives, as they learn that their tickets and wiki entries are entirely pointless.

**Comment by MylesBorins** [comment]
This is about nihilism not existentialism

**Comment by markmandel** [comment]
But one could argue that it is the deep understanding and authenticity of an existential moment that shows that the human condition had no intrinsic value or meaning, because the human mind sees in the manner that it is only aware of its own perception, and that perception is only important to itself.

But in the end, it doesn't really matter.

**Comment by MylesBorins** [comment]
I've locked this conversation because nothing matters

**Comment by MylesBorins** [comment]
The wiki has been removed because there is nothing worth documenting.

The issue tracker will remain because it is important for people to be told their issues do not matter
